// Expected: Throw('success')
let (x = 1)

try {
  throw "success"
} finally {
  "failure"
}
